# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-11 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=128)),
                ('client_contact', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time_expect', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('price_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_full', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('client_username', models.CharField(max_length=255, unique=True)),
                ('contact_phone', models.CharField(max_length=128, null='false')),
                ('contact_email', models.EmailField(max_length=128, null='false')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('first_name', models.CharField(max_length=64, unique=True)),
                ('last_name', models.CharField(max_length=64)),
                ('merchant_username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('employee_name', models.ForeignKey(db_column='first_name', on_delete=django.db.models.deletion.CASCADE, to='appointment.Employee', to_field='first_name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('service_name', models.CharField(max_length=128, unique=True)),
                ('duration', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service_booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('service', models.ForeignKey(blank=True, db_column='service_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Service', to_field='service_name')),
            ],
        ),
        migrations.CreateModel(
            name='Service_provided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('service', models.ForeignKey(blank=True, db_column='service_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Service', to_field='service_name')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_username', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Client', to_field='client_username'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee_created',
            field=models.ForeignKey(blank=True, db_column='first_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Employee', to_field='first_name'),
        ),
    ]
